apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendation-service
  description: Recommendation service
  annotations:
    backstage.io/techdocs-ref: dir:. # points to the documentation location and it should be docs
  tags:
    - javascript
  links:
    - url: https://google.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: experimental
  owner: guests
